# Generated by Django 6.0.5 on 2026-05-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_codeverify_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_status',
            field=models.CharField(choices=[('new', 'new'), ('code_verify', 'code_verify'), ('change_info', 'change_info'), ('change_done', 'change_done')], default='new', max_length=20),
        ),
    ]
